### ISSUE TITLE
gulp-util deprecated - use plugin-error instead

### ISSUE THREAD

**Issue by jpicton** [osaton/gulp-sass-variables#3]
As outlined in https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5, gulp-util has been deprecated. The fix in this case is fairly simple: instead of using gutil.PluginError, we'll need to use the plugin-error dependency in its place (https://github.com/gulpjs/plugin-error).

**Comment by osaton** [comment]
Thanks for the reminder!
